# fly.toml app configuration file generated for dev-links on 2024-01-15T21:08:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dev-links"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
